.gitmodules
packages/gelly-gmod/src/scene/Map.cpp

Meets the acceptance criteria of #47

47 - Revert BSPParser back to Derpius' BSPParser

---

lua/gelly/api/gx-soft-functions.lua

Meets the acceptance criteria of #51

51 - Remove particle queue and its associated particle spawning delay

---

packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp

Fulfills acceptance criteria for #54

54 - Ensure solid fill mode for all Gelly compositing calls

---

CHANGELOG.md
CMakeLists.txt
cmake/GetCurrentVersion.cmake
packages/gelly-gmod/CMakeLists.txt
packages/gelly-gmod/src/main.cpp
packages/gelly-gmod/src/version.h.in

Resolves #56 
- Adds a changelog
- Adds a version number from said changelog into CMake
- Exposes version number from the binary module

#56 - Add changelogs

---

.gitmodules
packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp
packages/gelly-gmod/src/hooking/Library.cpp
packages/gelly-gmod/src/logging/global-macros.cpp
packages/gelly-gmod/src/main.cpp
packages/gelly-gmod/src/source/GetCubemap.cpp
packages/gelly-gmod/src/source/IVEngineServer.h
packages/gelly-gmod/src/source/IVRenderView.cpp
packages/gelly/modules/gelly-fluid-renderer/include/fluidrender/IManagedShader.h
packages/gelly/modules/gelly-fluid-renderer/include/fluidrender/util/Exceptions.h
packages/gelly/modules/gelly-fluid-sim/CMakeLists.txt
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/CD3D11RTFRFluidSimulation.cpp
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/CFlexSImScene.cpp
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/CFlexSimRigids.cpp
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/rtfr/Dataset.h
packages/gsc/src/ShaderFile.cpp
packages/gsc/src/ShaderFileCompiler.h

None.
- Fixes all regressions when compiling with clang, notably fixing an *entirely* missing submodule for the fluid sim.

NONE - Fix all clang regressions

---

CMakeLists.txt
packages/gelly-gmod/src/logging/format-log-entry.cpp
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/rtfr/RTFRLoader.cpp

None.
- Adds sccache to Gelly, and makes it work very fast with clang

NONE - Add sccache support

---

packages/addon/lua/weapons/gelly_liquifier.lua

Resolves #62 
- Makes the liquifier use a c_pistol model to support playermodel hands

62 - Fix the Liquifier's hands

---

.github/workflows/create-production-release.yml

None.
- Fixes some typos in the CI script

NONE - Fix some typos in the CI scripts

---

.luarc.json

None
- Adds an IDE-invariant `.luarc.json` root config to point everything to the addon package
- Treat `include` like `require`

NONE - Configure LuaLS invariant of IDE

---

.github/pull_request_template.md

None
- Adds a GitHub PR template for tickets

NONE - Add PR template

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-update-check.lua

Resolves none
- Fixes an inverted condition that slipped into the #74 PR

NONE - Fix update check

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.gs50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.vs50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/SplattingStructs.hlsli

Resolves none
- Adds a new variance filter to the renderer, helping performance and visuals by eliminating tiny particles that don't contribute much to the final image.

NONE - New variance filter

---

CHANGELOG.md
packages/addon/lua/gelly/api/emitters/cube-emitter.lua
packages/addon/lua/gelly/api/emitters/mesh-emitter.lua
packages/addon/lua/gelly/api/emitters/sphere-emitter.lua
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/gx-soft-functions.lua

Resolves #84 
- Adds a material override to each emitter function
- Adds a function to copy preset materials

84 - Allow material overriding

---

CHANGELOG.md
packages/addon/lua/gelly/api/mods/manager.lua

Resolves none
- Makes the sandbox mod the default

NONE - Make sandbox mod default

---

CHANGELOG.md
packages/addon/lua/gelly/api/presets/immutable/water.lua
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Thickness.ps50.hlsl

Resolves 
- Changes the Water preset's absorption
- Removes thickness limit

NONE - Improve water

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-object-management.lua
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/presets/immutable/water.lua
packages/addon/lua/gelly/util/get-brush-model-mesh.lua
packages/gelly/modules/gelly-fluid-renderer/src/shaders/FilterDepth.ps50.hlsl

Resolves none
- Adds a convar to scale the radius of any preset that is loaded
- Adjusts the object management script to block non-physical entities

NONE - Add radius scaling

---

CHANGELOG.md
packages/gelly-gmod/src/composite/PipelineConfig.h
packages/gelly-gmod/src/shaders/Composite.ps30.hlsl
packages/gelly-gmod/src/shaders/util/CMRMap.hlsli
packages/gelly/modules/gelly-fluid-renderer/CMakeLists.txt
packages/gelly/modules/gelly-fluid-renderer/src/shaders/FilterDepth.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/pipelines/depth-filtering.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/pipelines/ellipsoid-splatting.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/pipelines/surface-filtering.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/pipelines/thickness-extraction.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.cpp
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/texture-registry.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/resources/texture.cpp

Resolves #90 
- Adds a new surface filter, which is a mix of a depth and normal filter.

90 - New surface filter

---

CHANGELOG.md
packages/gelly-gmod/src/main.cpp

Resolves 
- Fixes std::filesystem::remove causing exceptions

NONE - Fix remove error

---

.github/workflows/create-production-release.yml
CMakeLists.txt
packages/gelly-gmod/CMakeLists.txt

Resolves #118 
- Adds rcedit support to gelly-gmod
- Makes the pipeline download a copy of rcedit

118 - Add binary versioning

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.gs50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.vs50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/SplattingStructs.hlsli
packages/gelly/modules/gelly-fluid-renderer/src/shaders/util/SolveQuadratic.hlsli

Resolves 
- Rewrites most of the splatting pass to use intrinsics and less registers

NONE - Improve splatting shader

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h

Resolves 
- Lower filter iterations to 5
This was determined to be the lowest amount of iterations before individual particles would appear

NONE - Lower filter iterations

---

CHANGELOG.md
packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp
packages/gelly-gmod/src/composite/standard/StandardPipeline.h
packages/gelly-gmod/src/shaders/Composite.ps30.hlsl
packages/gelly-gmod/src/shaders/material/FluidMaterial.hlsli

Resolves 
- Gives the composite shader access to the VP matrix
- Tosses out the old refraction in favor of a guessed screen-space refraction

NONE - Add proper refraction

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Splatting.ps50.hlsl

Resolves 
- Feathers thickness
- Overall reduces the visible boundaries between particles

NONE - Feather thickness

---

CHANGELOG.md
packages/gelly-gmod/src/source/GetCubemap.cpp
packages/gelly-gmod/src/source/Signatures.h

…st GMod update
Resolves 
- Removes GetMaxLights
- Hardcodes maximum Source lights as four (doesn't make a difference)

NONE - Fix September 9th GMod patch breaking Gelly

---

CHANGELOG.md
packages/gelly-gmod/src/composite/standard/StandardTextures.cpp
packages/gelly/modules/gelly-fluid-renderer/src/shaders/AlbedoDownsample.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h

Resolves 
- Pushes the output scale from `0.1` to `0.25
- Cross filters thickness, gaussian blurs albedo

NONE - Tweak albedo scale

---

CHANGELOG.md
packages/addon/lua/entities/gelly_disc_emitter.lua

Resolves 
- Adds color overriding to emitters

NONE - Multi color emitters

---

CHANGELOG.md
packages/addon-ui/ui/components/CheckBox.css
packages/addon-ui/ui/components/CheckBox.tsx
packages/addon-ui/ui/pages/graphics.tsx
packages/addon-ui/ui/pages/presets.tsx
packages/addon/lua/autorun/client/gelly-sun-lighting.lua
packages/addon/lua/autorun/client/gelly-update-loop.lua
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/gx-settings.lua
packages/addon/lua/gelly/api/presets/immutable/blood.lua
packages/gelly-gmod/src/composite/PipelineConfig.h
packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp
packages/gelly-gmod/src/composite/standard/StandardPipeline.h
packages/gelly-gmod/src/main.cpp
packages/gelly-gmod/src/shaders/Composite.ps30.hlsl

Resolves 
- Adds `CheckBox` to the menu
- Constrains light spread for all specular radiance
- Adds two new functions to the raw Gelly Lua API to handle enabling/disabling sun and changing its position
- Hook up `IsSpecularTransmission` to the customization menu
- Remove several debug prints

NONE - Add sun lighting

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-developer-ui.lua
packages/gelly-gmod/CMakeLists.txt
packages/gelly-gmod/src/composite/GModCompositor.cpp
packages/gelly-gmod/src/composite/GModCompositor.h
packages/gelly-gmod/src/composite/Pipeline.h
packages/gelly-gmod/src/composite/reload-shaders.h
packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp
packages/gelly-gmod/src/composite/standard/StandardPipeline.h
packages/gelly-gmod/src/main.cpp
packages/gelly/modules/gelly-fluid-renderer/CMakeLists.txt
packages/gelly/modules/gelly-fluid-renderer/src/shaders/FilterDepth.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/FluidRenderCBuffer.hlsli
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/reload-shaders.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.cpp
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h
packages/gsc/src/GlueCodeGen.cpp
packages/gsc/src/GlueCodeGen.h
packages/gsc/src/ShaderFile.cpp
packages/gsc/src/ShaderFile.h
packages/gsc/src/ShaderFileCompiler.cpp
packages/gsc/src/ShaderFileCompiler.h
packages/gsc/src/main.cpp

Resolves 
- Adds a brand new surface filter which is an iteration of the previous one
- 9-point IGN-dispersed filter
- Each smoothing pass is correlated with the previous to remove noise
- Adds shader hotreloading to gelly-gmod and gelly-fluid-renderer
- Tightens the mip curve

NONE - New filter

---

CHANGELOG.md
packages/addon/lua/entities/gellyx_forcefield.lua

Resolves 
- Recreates forcefields upon a Gelly restart

NONE - Fix forcefields

---

.github/workflows/create-production-release.yml
packages/addon/lua/weapons/gelly_liquifier.lua

Resolves 
- Adds an emergency patch to no longer output a GMA in the release bundles
- Adds camera shake to liquifier

NONE - Fix addon output in pipeline

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-object-management.lua

This makes the prop_door_rotating entity collide with gelly
Resolves NONE
Adds collision to doors or the prop_door_rotating type (which are very common).

Added collisions to doors

---

CHANGELOG.md
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/gx-settings-sync.lua

Resolves #166 
- Checks if the whitewater rendering should be enabled given the preset

166 - Fix whitewater bug

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-sim/include/fluidsim/scene/handlers/shape-handler.cpp
packages/gelly/modules/gelly-fluid-sim/include/fluidsim/scene/handlers/shape-handler.h
packages/gelly/modules/gelly-fluid-sim/include/fluidsim/scene/object.h

Resolves 
- Defers the initialization of objects until we can confirm they have a valid position history

NONE - Fix teleportation bug for real

---

.idea/editor.xml
.idea/misc.xml
CHANGELOG.md
packages/addon/lua/gelly/util/prop-resizer.lua

Resolves 
- Adds early return when prop resizer is not installed

NONE - Fix prop resizer error 

---

CHANGELOG.md
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/CD3D11FlexFluidSimulation.cpp

Resolves 
- Changes smoothing from `2.2` to `1.0`

NONE - Fix smoothing

---

.idea/editor.xml
CHANGELOG.md
packages/addon-ui/ui/pages/simulation.tsx
packages/addon/lua/gelly/api/gx-settings-sync.lua
packages/addon/lua/gelly/api/gx-settings.lua
packages/addon/lua/weapons/gelly_liquifier.lua
packages/gelly-gmod/src/composite/PipelineConfig.h
packages/gelly-gmod/src/composite/standard/StandardPipeline.cpp
packages/gelly-gmod/src/composite/standard/StandardPipeline.h
packages/gelly-gmod/src/main.cpp
packages/gelly-gmod/src/shaders/Composite.ps30.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h

Resolves 
- Adds whitewater strength slider
- Tweaks refraction
- Fixes liquifier

NONE - Tune whitewater and refraction

---

CHANGELOG.md
packages/addon-ui/ui/pages/presets.tsx
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/gx-settings.lua
packages/addon/lua/gelly/api/presets/immutable/blood.lua
packages/addon/lua/gelly/api/presets/immutable/gello.lua
packages/addon/lua/gelly/api/presets/immutable/piss.lua
packages/addon/lua/gelly/api/presets/immutable/water.lua
packages/gelly/modules/gelly-fluid-sim/src/fluidsim/CD3D11FlexFluidSimulation.cpp

Resolves #177 
- Exposes surface tension
- Scales surface tension with radius

177 - Expose surface tension

---

README.md

Resolves 
- Adds discord badge

NONE - Add discord badge to README

---

CHANGELOG.md
packages/gelly-gmod/src/source/Signatures.h

Patch signatures for Jan 29th update

---

packages/addon-ui/ui/components/CheckBox.css
packages/addon-ui/ui/components/Slider.css
packages/addon-ui/ui/customization.css
packages/addon-ui/ui/customization.tsx
packages/addon-ui/ui/gelly.d.ts
packages/addon-ui/ui/layouts/SlidersExplanationLayout.css
packages/addon-ui/ui/pages/presets.tsx
packages/addon-ui/ui/pages/simulation.tsx
packages/addon/lua/autorun/client/gelly-update-loop.lua
packages/addon/lua/gelly/api/gx-fluid-presets.lua
packages/addon/lua/gelly/api/gx-settings-sync.lua
packages/addon/lua/gelly/api/gx-settings.lua
packages/addon/lua/gelly/ui/customization.lua

Resolves #218 
Resolves #215 
- Redesigns some parts of the UI to look compact and sleeker
- Adds multiple ways to escape the menu
- Remove radius scaling
- Add correct preset setting resets

NONE - Multiple hotfixes

---

CHANGELOG.md
packages/addon-ui/ui/components/PresetMenu.css
packages/addon-ui/ui/components/PresetMenu.tsx
packages/addon-ui/ui/gelly-sync.ts
packages/addon-ui/ui/gelly.d.ts
packages/addon-ui/ui/pages/presets.tsx
packages/addon/lua/autorun/client/gelly-initialize.lua
packages/addon/lua/gelly/api/gx-init.lua
packages/addon/lua/gelly/api/presets/immutable/blood.lua
packages/addon/lua/gelly/api/presets/immutable/gallium.lua
packages/addon/lua/gelly/api/presets/immutable/gello.lua
packages/addon/lua/gelly/api/presets/immutable/gelq.lua
packages/addon/lua/gelly/api/presets/immutable/glunk.lua
packages/addon/lua/gelly/api/presets/immutable/milk.lua
packages/addon/lua/gelly/api/presets/immutable/piss.lua
packages/addon/lua/gelly/api/presets/immutable/water.lua
packages/addon/lua/gelly/ui/customization.lua

Resolves #220 
- Adds a preset menu to the customization menu
- Add Gelq
- Add Gallium
- Add Milk

220 - Preset menu

---

CHANGELOG.md

Fix Gelly 1.33

---

CHANGELOG.md
packages/addon/lua/gelly/api/gx-init.lua
packages/addon/lua/gelly/api/mods/manager.lua
packages/addon/lua/html/welcome_screen.css.lua
packages/addon/lua/html/welcome_screen.html.lua

Resolves 
- Fixes welcome screen
- Fixes mod deadlock situation

NONE - 1.33 patches

---

CHANGELOG.md

Fix changelog version number

---

CHANGELOG.md
packages/addon-ui/ui/pages/graphics.tsx
packages/addon-ui/ui/pages/presets.tsx
packages/addon/lua/autorun/client/gelly-update-loop.lua
packages/addon/lua/gelly/api/emitters/cube-emitter.lua
packages/addon/lua/gelly/api/gx-settings-sync.lua
packages/addon/lua/gelly/api/gx-settings.lua
packages/addon/lua/gelly/api/gx-soft-functions.lua
packages/addon/lua/gelly/api/presets/immutable/gallium.lua
packages/addon/lua/weapons/gelly_gun.lua
packages/gelly-gmod/src/main.cpp
packages/gelly-gmod/src/scene/ParticleManager.cpp
packages/gelly-gmod/src/scene/ParticleManager.h
packages/gelly-gmod/src/source/Signatures.h
packages/gelly/modules/gelly-fluid-renderer/src/shaders/FilterDepth.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/Foam.ps50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/shaders/SplattingNoCull.gs50.hlsl
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/pipelines/ellipsoid-splatting.h
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.cpp
packages/gelly/modules/gelly-fluid-renderer/src/v2/renderers/splatting/splatting-renderer.h
packages/gelly/modules/gelly-fluid-sim/src/v2/solver.cpp
packages/gelly/modules/gelly-fluid-sim/src/v2/solver.h

Resolves 
- Adds raw normals support
- No particle cull support
- Gallium is tuned
- Customizable particle mass and anisotropy
- Filter now adjusts its minimum dynamically

NONE - Plenty of random features and signature fix

---

CHANGELOG.md
packages/gelly-gmod/src/main.cpp

NONE - Fix culling randomly rolling back

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-bullet-physics.lua
packages/addon/lua/autorun/client/gelly-object-management.lua
packages/addon/lua/autorun/server/gelly-replicate-bullets.lua
packages/addon/lua/gelly/api/gx-init.lua
packages/addon/lua/gelly/api/gx-replicate-bullets.lua

NONE - Add bullet physics

---

packages/addon/lua/weapons/gelly_gun.lua

Resolves NONE
Fixes a long time issue of the Gelly Gun not compensating for the higher radii fluid.

Gelly Gun correct density compensation

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-explosion-physics.lua
packages/addon/lua/autorun/server/gelly-replicate-explosions.lua
packages/addon/lua/gelly/api/gx-init.lua
packages/addon/lua/gelly/api/gx-replicate-explosions.lua
packages/addon/lua/gelly/api/presets/immutable/blood.lua
packages/addon/lua/weapons/gelly_gun.lua

NONE - Explosion physics and density adjustments for the Gelly Gun

---

CHANGELOG.md
packages/addon/lua/autorun/client/gelly-performance-command.lua
packages/addon/lua/gelly/api/presets/immutable/blood.lua
packages/addon/lua/gelly/util/timing-sampler.lua

NONE - Fix blood preset and performance debugger

---

.github/workflows/create-production-release.yml

NONE - Update sccache action version
